######################################################
#
# CURRENT_VERSION: vedi sotto (DRY)
#
# = HISTORY =
#
# v1.7 2020-12-01 Copied from sinatroccolo
---
options:
    machineType: 'N1_HIGHCPU_8'
timeout: 600s
tags: ['cb-trigger', 'from-sinatroccolo', 'ror5', 'tag-$TAG_NAME']
#images:
#    - 'gcr.io/$PROJECT_ID/ror5-gceregions'
steps:
    - name: bash # 'gcr.io/cloud-builders/docker'
      id: 00 Lets make sure MAKE exists 
      entrypoint: 'which'
      args:
        - 'make'

        # 1. Build Dockerfile
    - name: bash # 'gcr.io/cloud-builders/docker'
      id: 00 Lets try make build from another execution strategy without bash
      entrypoint: 'make'
      args:
        - 'docker-build'


    # 1. Build Dockerfile
    - name: 'gcr.io/cloud-builders/docker'
      id: 01 Build Docker File with bash and make
      entrypoint: 'bash'
      args:
        - '-eEuo'
        - 'pipefail'
        - '-c'
        - 'make'
        - 'docker-build'

    # 2. Create tags and pushes them
    - name: 'gcr.io/cloud-builders/gcloud'
      id: 02 Tag locally to both vVER and LATEST and push both
      entrypoint: 'bash'
      args:
          - '-eEuo'
          - 'pipefail'
          - '-c'
          - 'make'
          - 'docker-push-to-gcp'
