version: '3'
services:
  db:
    image: postgres:10.1-alpine
  web:
    build: .
    command: bin/rails s -p 8080 -b '0.0.0.0'
    volumes:
      - .:/usr/src/app
    ports:
      - "8080:8080"
    depends_on:
      - db
